const config = {
  style: "mapbox://styles/mapbox/light-v10",
  accessToken:
    "pk.eyJ1IjoiZ3RtcHJrc2hyYiIsImEiOiJjamZ0bXBqZnMxd3E5MnduejVjdGpuN2R4In0.vvrRpEdZWNwaKUO6vmgRHw",
  CSV: "https://docs.google.com/spreadsheets/d/1oWyyvyJTPuxjIFY8RWRaZjbbSAl8ZQO3SJ9nTUK6SeY/gviz/tq?tqx=out:csv&sheet=data",
  center: [76.081918, 11.6285225],
  zoom: 10,
  title: "City Dashboard",
  description:
    "Crowdsourced Rainfall Data by Hume Centre for Ecology and Wildlife Biology",
  sideBarInfo: ["LOCATION", "rainfall"],
  popupInfo: ["rainfall"],
  filters: [
    {
      type: "dropdown",
      title: "Panchayat: ",
      columnHeader: "PANCHAYAT CODE",
      listItems: [
        "MEP",
        "POZ",
        "VEN",
        "KAL",
        "MUT",
        "AMB",
        "BAT",
        "NOOL",
        "VEL",
        "THO",
        "PAN",
        "EDA",
        "MAN",
        "PUL",
        "THAV",
        "THI",
        "VYT",
        "MOOP",
        "THAR",
        "NEN",
        "PAD",
        "KOT",
        "MEEN",
        "POOT",
        "MUL",
      ],
    },
  ],
};
